name: Gpdviz tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: postgres
      - uses: CasperWA/postgresql-action@v1.2
        with:
          postgresql version: '14'
          postgresql db: gpdviz
          postgresql port: 2345
      - name: Build and Test
        run: |
          cd backend
          sbt test
